Addressed potential linker issues with JNI_OnLoad in Platform::Android
Summary:
In case several libraries with their own "JNI_OnLoad" functions are linked together, we may end with linker issues due to dublicated symbols - e.g.,

```
error: duplicate symbol: JNI_OnLoad"
```

This diff fixes the issue by adding `fbandroid_allow_jni_merging = True,` to the BUCK target and removing the declaration of the function.

Reviewed By: enpe

Differential Revision: D55260975

fbshipit-source-id: 0104d4253fea5ac624cf347e4b04c8ac26dbe345