Fix config of iOS test apps (#21)
Summary:
The list of source files of these apps included files that are only meant for the desktop versions of these test apps. They need to be excluded from iOS builds in order to avoid linker errors about duplicate symbols similar to this:

```
ld: warning: ignoring duplicate libraries: '/Users/nils/build_ocean_ios_release/impl/ocean/base/Debug-iphoneos/libocean_base.a', '/Users/nils/build_ocean_ios_release/impl/ocean/test/testcv/Debug-iphoneos/libocean_test_testcv.a'
duplicate symbol '_main' in:
    /Users/nils/build_ocean_ios_release/build/application_ocean_test_cv_testcv_testsegmentation_ios.build/Debug-iphoneos/Objects-normal/arm64/Main.o
    /Users/nils/build_ocean_ios_release/build/application_ocean_test_cv_testcv_testsegmentation_ios.build/Debug-iphoneos/Objects-normal/arm64/TestCVSegmentation.o
ld: 1 duplicate symbols
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Pull Request resolved: https://github.com/facebookresearch/ocean/pull/21

Test Plan:
On a Mac, follow the instructions for iOS builds:

https://github.com/facebookresearch/ocean/blob/main/building_for_ios.md

Then, build, install, and start each of the following targets from XCode:

* `application_ocean_test_base_testbase_ios`
* `application_ocean_test_cv_testcv_ios`
* `application_ocean_test_cv_testcv_testadvanced_ios`
* `application_ocean_test_cv_testcv_testdetector_ios`
* `application_ocean_test_cv_testcv_testdetector_testqrcodes_ios`
* `application_ocean_test_cv_testcv_testsegmentation_ios`
* `application_ocean_test_geometry_testgeometry_ios`
* `application_ocean_test_math_testmath_ios`
* `application_ocean_test_media_testmedia_ios`
* `application_ocean_test_platform_testplatform_ios`
* `application_ocean_test_tracking_testtracking_ios`

Reviewed By: ASchneiderMeta

Differential Revision: D59739623

Pulled By: enpe

fbshipit-source-id: 99f5c2622483555b9f38eb7c67fd3027c1c06e33