Update android manifests for camera demos
Summary:
Adding <uses-feature android:name="android.hardware.camera" /> to manifests for demos that require camera fixes lint errors that occur when building w/ gradle.

```
Error: Permission exists without corresponding hardware <uses-feature android:name="android.hardware.camera" required="false"> tag [PermissionImpliesUnsupportedChromeOsHardware]
      <uses-permission android:name="android.permission.CAMERA" />
       ~~~~~~~~~~~~~~~
```

Reviewed By: enpe

Differential Revision:
D57802515

Privacy Context Container: L1191897

fbshipit-source-id: 627f2acb175b8c895eac43bef4ab86079dd0533c