@NSApplicationMain -> @main
Summary:
There are nooks and crannies across fbsource that were using Xcode instead of Meta's de-facto Apple compiler, Pika. These are being exposed by D82215873.
Pika is generally more strict, and we're seeing some compilation errors.

```
xplat/ocean/impl/application/ocean/demo/platform/osxswift/osx/MainWindow_V3.swift:10:1: error: 'NSApplicationMain' is deprecated; this is an error in the Swift 6 language mode
  8 | import Cocoa
  9 |
 10 | NSApplicationMain
    | |- error: 'NSApplicationMain' is deprecated; this is an error in the Swift 6 language mode
    | `- note: use 'main' instead
 11 | class AppDelegate:
 12 |   NSObject,
```

Reviewed By: drodriguez

Differential Revision: D82564182

fbshipit-source-id: 4cc528bf1b4106645a021f703407e8ef37c179b2