fix deprecated usage in ios:ocean::openglframemediumview controller
Summary:
property 'mainScreen' is declared deprecated here, instead use view.window.windowScene.screen as prompted by compiler

```
Action failed: fbsource//xplat/ocean/impl/ocean/platform/apple/ios:iosApple (objcxx_compile OpenGLFrameMediumViewController.mm (pic))
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action a49c19cfc88c76eb23dbc5cbfe7805becdccaf60924dd057367eb79dd8af256f:145`
stdout:
stderr:
clang++: warning: argument '-Ofast' is deprecated; use '-O3 -ffast-math' for the same behavior, or '-O3' to enable only conforming optimizations [-Wdeprecated-ofast]
xplat/ocean/impl/ocean/platform/apple/ios/OpenGLFrameMediumViewController.mm:163:32: error: 'mainScreen' is deprecated: first deprecated in iOS 26.0 - Use a UIScreen instance found through context instead (i.e, view.window.windowScene.screen), or for properties like UIScreen.scale with trait equivalents, use a traitCollection found through context. [-Werror,-Wdeprecated-declarations]
  163 |         const float scale = [UIScreen mainScreen].scale;
      |                                       ^
buck-out/v2/gen/fbsource/5da81dfcec7d377b/xplat/toolchains/apple/__xcode_26.0.0_17a324-iphoneos-sdk_genrule-actual__/iPhoneOS26.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIScreen.h:57:49: note: property 'mainScreen' is declared deprecated here
   57 | property(class, nonatomic, readonly) UIScreen *mainScreen API_DEPRECATED("Use a UIScreen instance found through context instead (i.e, view.window.windowScene.screen), or for properties like UIScreen.scale with trait equivalents, use a traitCollection found through context.", ios(2.0, 26.0), tvos(9.0, 26.0), visionos(1.0, 26.0)) API_UNAVAILABLE(watchos);
      |                                                 ^
buck-out/v2/gen/fbsource/5da81dfcec7d377b/xplat/toolchains/apple/__xcode_26.0.0_17a324-iphoneos-sdk_genrule-actual__/iPhoneOS26.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIScreen.h:57:49: note: 'mainScreen' has been explicitly marked deprecated here
1 error generated.
[apple_cxx_error_deprecated_declarations] xplat/ocean/impl/ocean/platform/apple/ios/OpenGLFrameMediumViewController.mm:163:32 'mainScreen' is deprecated: first deprecated in iOS 26.0 - Use a UIScreen instance found through context instead (i.e, view.window.windowScene.screen), or for properties like UIScreen.scale with trait equivalents, use a traitCollection found through context. [-Wdeprecated-declarations]
[apple_cxx_note] buck-out/v2/gen/fbsource/5da81dfcec7d377b/xplat/toolchains/apple/__xcode_26.0.0_17a324-iphoneos-sdk_genrule-actual__/iPhoneOS26.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIScreen.h:57:49 property 'mainScreen' is declared deprecated here
[apple_cxx_note] buck-out/v2/gen/fbsource/5da81dfcec7d377b/xplat/toolchains/apple/__xcode_26.0.0_17a324-iphoneos-sdk_genrule-actual__/iPhoneOS26.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIScreen.h:57:49 'mainScreen' has been explicitly marked deprecated here
Interaction with installer failed.

Caused by:
    Failed to build 'fbsource//xplat/ocean/impl/ocean/platform/apple/ios:iosApple (cfg:iphoneos-arm64-iphoneos-clang19#d8b5bb04c0f4a541)'
```

Differential Revision: D85386226

fbshipit-source-id: c6c7f7dac75194e13e94c655d8af698b9b8634cd